import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Metadata } from "next"; // Добавляем тип для metadata

// Типы для пропсов (оставляем существующие шрифты без изменений)
interface RootLayoutProps {
  children: React.ReactNode;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Добавляем тип Metadata, но сохраняем текущие значения
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Добавляем тип для пропсов, но не меняем логику
export default function RootLayout({ children }: RootLayoutProps) {
  return (
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {children}
      </body>
      </html>
  );
}
